apiVersion: v1
kind: ConfigMap
metadata:
  name: medflow-config
  namespace: medflow
  labels:
    app.kubernetes.io/name: medflow-config
    app.kubernetes.io/part-of: medicore360
data:
  NODE_ENV: "production"
  PORT: "4000"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://medicore360.com"
  MONGODB_DB_NAME: "medicore_production"
  NEXT_PUBLIC_API_URL: "https://medicore360.com/api/v1"
