apiVersion: v1
kind: Secret
metadata:
  name: medflow-secrets
  namespace: medflow
  labels:
    app.kubernetes.io/name: medflow-secrets
    app.kubernetes.io/part-of: medicore360
type: Opaque
stringData:
  MONGODB_URI: "mongodb://medflow-mongodb.medflow.svc.cluster.local:27017/medicore_production"
  REDIS_URL: "redis://medflow-redis.medflow.svc.cluster.local:6379"
  JWT_SECRET: "k8s-prod-super-secure-jwt-secret-key-32-chars-min"
  AUTH_PEPPER: "k8s-prod-pepper-secret-key-salt-2026"
  SMTP_HOST: "mailpit.medflow.svc.cluster.local"
  SMTP_PORT: "1025"
